on: [push]
name: "CI"

jobs:
  test:
    name: Astro Test
    strategy:
      matrix:
        node-versions: [16]
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-versions }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-versions }}

    - name: Install dependencies
      run: npm install --frozen-lockfile

    - name: Build
      run: npm run build
