on:
  push:
    branches:
      - master
name: "Deploy"

jobs:
  publish-docs:
    name: gh-pages
    strategy:
      matrix:
        node-versions: [20]
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Install dependencies
        run: npm install --production --unsafe-perm

      - name: Export
        run: npm run build

      - name: .nojekyll
        run: touch ./dist/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages